export enum ActionTypeKeys {
    UPDATE_MOUSE_COORDS                     = 'UPDATE_MOUSE_COORDS',
    DISPLAY_MODAL                           = 'DISPLAY_MODAL',
    CLEAR_MODAL                             = 'CLEAR_MODAL',
    TOGGLE_MAXIMIZE_INFO_PANEL              = 'TOGGLE_MAXIMIZE_INFO_PANEL',
    SET_PANE_TO_OPEN_INFO_PANEL             = 'SET_PANE_TO_OPEN_INFO_PANEL',
    NEW_TARGET                              = 'NEW_TARGET',
    UNSET_TARGET                            = 'UNSET_TARGET',
    ADD_TOAST                               = 'ADD_TOAST',
    DISMISS_TOAST                           = 'DISMISS_TOAST',
    GET_TREE_INFO_IN_PROGRESS               = 'GET_TREE_INFO_IN_PROGRESS',
    GET_FEAT_NUM_PHOTOS_IN_PROGRESS         = 'GET_FEAT_NUM_PHOTOS_IN_PROGRESS',
    GET_FEAT_PHOTO_IN_PROGRESS              = 'GET_FEAT_PHOTO_IN_PROGRESS',
    DEL_FEAT_PHOTO_IN_PROGRESS              = 'DEL_FEAT_PHOTO_IN_PROGRESS',
    GET_FEAT_AJAX_CONCLUDED                 = 'GET_FEAT_AJAX_CONCLUDED',
    GET_TREE_INFO_SUCCESS                   = 'GET_TREE_INFO_SUCCESS',
    GET_FEAT_NUM_PHOTOS_SUCCESS             = 'GET_FEAT_NUM_PHOTOS_SUCCESS',
    GET_FEAT_PHOTO_SUCCESS                  = 'GET_FEAT_PHOTO_SUCCESS',
    SET_TREE_INFO_CURRENT                   = 'SET_TREE_INFO_CURRENT',
    SET_TREE_INFO_ORIGINAL                  = 'SET_TREE_INFO_ORIGINAL',
    REVERT_TREE_INFO                        = 'REVERT_TREE_INFO',
    SET_TREE_COORDS_ORIGINAL                = 'SET_TREE_COORDS_ORIGINAL',
    SET_TREE_COORDS                         = 'SET_TREE_COORDS',
    REVERT_TREE_COORDS                      = 'REVERT_TREE_COORDS',
    GET_REGIONS_IN_PROGRESS                 = 'GET_REGIONS_IN_PROGRESS',
    GET_REGIONS_SUCCESS                     = 'GET_REGIONS_SUCCESS',
    UPDATE_SELECTED_REGIONS                 = 'UPDATE_SELECTED_REGIONS ',
    OVERLAPS_UPDATE_SELECTED_REGION         = 'OVERLAPS_UPDATE_SELECTED_REGION',
    OVERLAPS_GET_REGIONS_SUCCESS            = 'OVERLAPS_GET_REGIONS_SUCCESS',
    OVERLAPS_SET_REGION                     = 'OVERLAPS_SET_REGION',
    OVERLAPS_SET_PARTITIONS                 = 'OVERLAPS_SET_PARTITIONS',
    OVERLAPS_GET_OVERLAPS_IN_PROGRESS       = 'OVERLAPS_GET_OVERLAPS_IN_PROGRESS',
    OVERLAPS_GET_OVERLAPS_SUCCESS           = 'OVERLAPS_GET_OVERLAPS_SUCCESS',
    UPDATE_CONFIGURATION                    = 'UPDATE_CONFIGURATION',




    LOGIN                                   = 'LOGIN',

    SET_RGE_MODE                            = 'SET_RGE_MODE',
    SET_WKT_REGION_UNDER_CONSTRUCTION       = 'SET_WKT_REGION_UNDER_CONSTRUCTION',
    REG_MGMNT_DELETE_START                  = 'REG_MGMNT_DELETE_START',
    REG_MGMNT_DELETE_END                    = 'REG_MGMNT_DELETE_END',
    REG_MGMNT_MODIFY_START                  = 'REG_MGMNT_MODIFY_START',
    REG_MGMNT_MODIFY_END                    = 'REG_MGMNT_MODIFY_END',


    UPDATE_TREES                            = 'UPDATE_TREES'
}


