export const CHANGE_TILE_PROVIDER = "CHANGE_TILE_PROVIDER";
export const UPDATE_MOUSE_COORDS  = "UPDATE_MOUSE_COORDS";
export const TOGGLE_MODE          = "TOGGLE_MODE";
export const CLEAR_FLAG           = "CLEAR_FLAG";
export const ADD_POINT_TO_POLYGON_UNDER_CONSTRUCTION = "ADD_POINT_TO_POLYGON_UNDER_CONSTRUCTION";
export const DISPLAY_MODAL        = "DISPLAY_MODAL";

