export const DELETE_GEOMETRY_UNDER_DEFINITION = "DELETE_GEOMETRY_UNDER_DEFINITION";
export const CLEAR_DRAW_WORKSPACE             = "CLEAR_DRAW_WORKSPACE";
export const INSERT_GEOJSON_INTO_WORKSPACE    = "INSERT_GEOJSON_INTO_WORKSPACE";
